import React from 'react';

import type { Metadata } from 'next';
import 'primeflex/primeflex.css';
import 'primeicons/primeicons.css';
import { PrimeReactProvider } from 'primereact/api';
import 'primereact/resources/primereact.css';
import 'primereact/resources/themes/lara-light-cyan/theme.css';

import { AppProvider } from 'context';
import { ModalProvider } from 'context/modalContext';
import { EditPopup } from 'components';

import './globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
	return (
		<html lang="en">
			<body className={`antialiased`}>
				<div id='modal-container' className='absolute' />
				<PrimeReactProvider>
					<AppProvider>
						<ModalProvider>
							{children}
							<EditPopup />
						</ModalProvider>
					</AppProvider>
				</PrimeReactProvider>
			</body>
		</html>
	);
};
export default RootLayout;